package cuc.edu.cn.hynnsapp02.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cuc.edu.cn.hynnsapp02.domain.CollectionList;

import cuc.edu.cn.hynnsapp02.greendao.CollectionListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionListDaoConfig;

    private final CollectionListDao collectionListDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionListDaoConfig = daoConfigMap.get(CollectionListDao.class).clone();
        collectionListDaoConfig.initIdentityScope(type);

        collectionListDao = new CollectionListDao(collectionListDaoConfig, this);

        registerDao(CollectionList.class, collectionListDao);
    }
    
    public void clear() {
        collectionListDaoConfig.clearIdentityScope();
    }

    public CollectionListDao getCollectionListDao() {
        return collectionListDao;
    }

}
